development:
  adapter: mongodb
  host: store
  database: amibetter_dev

test:
  adapter: mongodb
  host: localhost
  database: amibetter_test

production:
  adapter: mongodb
  host: localhost
  database: amibetter_prod

